### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by BarbzYHOOL** [stefanheule/smartless#13]
How can we have colors?

Should I look about adding colors to less and it will work fine with smartless?

**Comment by stefanheule** [comment]
`smartless` already supports colors.  Do you have an example where it does not work?  You might have to explicitly tell the tool your want to output color to do so, as some tools try to detect when they can output colors, and fail to detect correctly if you use `smartless` (or `less`, for that matter).  E.g., use `git diff --color=always`.

Please re-open if there actually is a problem, and give an example of where color does not work.

**Comment by BarbzYHOOL** [comment]
No it's okay :)
