### ISSUE TITLE
Is it obsolete?

### ISSUE THREAD

**Issue by BarbzYHOOL** [stefanheule/smartless#14]
I was enjoying smartless but I just realized that with less we can pass this "-FX" and it does almost the same thing as smartless.

The only notable difference imo, is that we can define the amount of lines displayed with smartless.

**Comment by stefanheule** [comment]
I don't think so, because `less -XF` breaks scrolling, which was essentially the motivation to write smartless (see my [blog post for more history](https://stefanheule.com/blog/posts/2015-06-07/smartless-a-better-pager-for-small-and-large-inputs/)).  If there is now a way to use less without breaking scrolling, I would definitely be interested.

**Comment by BarbzYHOOL** [comment]
I just retried to be sure.

For long documents = no difference
For small documents = Smartless exits immediately but Less exits only after pressing "q". also if you press the up arrow with Less, you get an horrible spam of `~` but that's for a misspress

That's the only difference I've seen. I don't understand the "scrolling broken" thing

**Comment by stefanheule** [comment]
By scrolling is broken, I mean that the scrollwheel (on the mouse) does not work correctly.  It does with `smartless`, and `less` (without `-FX`).

**Comment by BarbzYHOOL** [comment]
With both I can scroll up but not scroll down unless I use pg down first. So dunno :P

You should try both.

**Comment by hkdobrev** [comment]
Less works in the same way after version 533. See the next answer in the Q&A you've linked from your blog post: https://unix.stackexchange.com/a/432254/27627

I've tried locally and it works the same as `smartless` after setting up the `$LESS` flags.

`less --mouse` gives you mouse wheel scrolling support out of the box. Keep in mind this might slightly depend on OS, terminal app and shell integration.
Use `--wheel-lines=N` where `N` is number of lines for a single scroll to control the paging when scrolling slowly with the mouse wheel or trackpad.
