### ISSUE TITLE
multiple files on input

### ISSUE THREAD

**Issue by mckellygit** [stefanheule/smartless#18]
Hi,
Thank you for smartless, it is great for me.
I added a small change to revert to original less if there are > 1 input file specified.  Is it worth a PR ?
```
  if [[ ! $var = -* ]] && [[ ! $var = +* ]]; then
    ((isfile++))
    file=$var
....
# if more than one file provided on cmdline, revert to original less ...
if (( isfile > 1 )); then
    exec less $@
fi
```
thx,
-m

**Comment by stefanheule** [comment]
Happy to accept and merge a PR if you send one. Thanks for contributing!

**Comment by mckellyln** [comment]
Hi,
See -
https://github.com/stefanheule/smartless/pull/19
thx,
-m

**Comment by stefanheule** [comment]
Thanks!
