### ISSUE TITLE
(END) marker not appearing if trackpad scrolling is used

### ISSUE THREAD

**Issue by waldyrious** [stefanheule/smartless#6]
If I use the space bar to paginate, the `(END)` marker appears once I reach the end of the document, but if instead I scroll with the mouse wheel or trackpad, no marker is shown.

If it helps, I'm using OS X Yosemite (10.10.5), and `bash --version` returns: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)`.

**Comment by stefanheule** [comment]
Is the behavior of the pager you use (it defaults to less) with the options used (defaults to `-iR --quiet`) correct, and the issue only appear when you use smartless?

**Comment by waldyrious** [comment]
Indeed, using unadorned `less` works as expected, but `less -iR --quiet` reproduces this issue (it actually seems to hang the console for a bit, but this is not related to smartless). It seems that `--quiet` is the culprit, since using just `-iR` doesn't reproduce the issue. Is it essential for `smartless` to work? Otherwise I would suggest sticking to as close as a clean `less` invocation as possible.

**Comment by stefanheule** [comment]
Aha.  No, it is not technically required, but I prefer to have it.  But you have a point to keep smartless clean, so I will remove it from the default option.  For me (and anyone else who likes to have --quiet as their argument), they can just set the env variable `SMARTLESS_PAGER_ARGUMENTS`.

**Comment by waldyrious** [comment]
Thanks :D
